name: Publish to GitHub Packages and Maven Central Portal

on:
    release:
        types:
          - created
    workflow_dispatch:

permissions:
    contents: read
    packages: write

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v4

          - name: Setup Java
            uses: actions/setup-java@v4
            with:
                java-version: 21
                distribution: temurin

          - name: Setup Gradle
            uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

          - name: Build
            run: ./gradlew build

          - name: Publish to GitHub Packages
            run: ./gradlew deployGithub
            env:
                GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          - name: Publish to Maven Central Portal
            run: ./gradlew deployCentralPortal
            env:
                CENTRAL_PORTAL_USERNAME: ${{ secrets.CENTRAL_PORTAL_USERNAME }}
                CENTRAL_PORTAL_PASSWORD: ${{ secrets.CENTRAL_PORTAL_PASSWORD }}
                GPG_KEY: ${{ secrets.GPG_KEY }}
                GPG_PWD: ${{ secrets.GPG_PWD }}
