name: Publish to Maven Central (OSSRH)

on:
    release:
        types:
          - created
    workflow_dispatch:

permissions:
    contents: read
    packages: write

jobs:
    publish-pkg-ossrh:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v4

          - name: Setup Java
            uses: actions/setup-java@v4
            with:
                java-version: 21
                distribution: temurin

          - name: Setup Gradle
            uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

          - name: Publish
            run: ./gradlew publish
            env:
                OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
                OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
                ORG_GRADLE_PROJECT_signingKey: ${{ secrets.GPG_KEY }}
                ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.GPG_PWD }}
